Signature: UnboundLocalError: local variable 'correct' referenced before assignment (file "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 33, in custom_show)
from #worldev-bots at 2016-06-07 19:11:45.501624:
Message was: <NeoMahler> .show test
Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 33, in custom_show
    msg = correct.split("||||")[1]
UnboundLocalError: local variable 'correct' referenced before assignment
----------------------------------------

Signature: UnboundLocalError: local variable 'msg' referenced before assignment (file "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 34, in custom_show)
from #worldev-bots at 2016-06-07 19:13:10.204528:
Message was: <NeoMahler> .show test
Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 34, in custom_show
    bot.say(msg)
UnboundLocalError: local variable 'msg' referenced before assignment
----------------------------------------

Signature: IndexError: list index out of range (file "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom)
from #worldev-bots at 2016-06-07 19:17:29.978361:
Message was: <NeoMahler> .custom add test hi
Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom
    key = trigger.group(3).split()[1]
IndexError: list index out of range
----------------------------------------

Signature: IndexError: list index out of range (file "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom)
from #worldev-bots at 2016-06-07 19:18:52.979317:
Message was: <NeoMahler> .custom add test hi
Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom
    key = trigger.group(3).split()[1]
IndexError: list index out of range
----------------------------------------

